name: Ruby Lint CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read

jobs:
  lint:
    if: ${{ github.repository == 'GoogleCloudPlatform/functions-framework-ruby' }}
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          github.com:443
          index.rubygems.org:443
          objects.githubusercontent.com:443
          release-assets.githubusercontent.com:443
          rubygems.org:443

    - name: Checkout repo
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - name: Install Ruby 3.1
      uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
      with:
        ruby-version: "3.4.10"
        bundler-cache: true
    - name: Install toys
      run: gem install --no-document toys
    - name: Lint
      run: "toys ci --only --test-rubocop"
