name: "Push docs to gh-pages"

on:
  release:
    types: [published]

# Declare default permissions as read only.
permissions: read-all

jobs:
  push-gh-pages:
    env:
      ruby_version: "3.1"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - name: Checkout repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install Ruby ${{ env.ruby_version }}
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          ruby-version: ${{ env.ruby_version }}
          bundler-cache: true
      - name: Install toys
        run: gem install --no-document toys
      - name: Publish docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          toys release publish-gh-pages --verbose < /dev/null
